trigger:
  branches:
    include:
      - v0.7-auth

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: CreateUbuntuBianary
    steps:
      - script: |
          sudo apt-get update
          sudo apt install -y autogen autoconf libtool libssl-dev
        displayName: "Install make dependencies"

      - script: |
          cd $(Build.SourcesDirectory)
          autoreconf -fvi
          ./configure
          make
        displayName: "Compile application"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact"
        inputs:
          PathToPublish: $(Build.SourcesDirectory)/src/dynomite
          ArtifactName: dynomite

      - task: DownloadSecureFile@1
        displayName: 'Download Ansible Vault Secure File'
        name: ansibleVault
        inputs:
          secureFile: 'bees-platform-ansible-vault-non-prod.secret'

      - script: |
          cat $(ansibleVault.secureFilePath)
