trigger:
  branches:
    includes:
      - v0.7-auth

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Create Ubuntu Bianary
    steps:
      - script: |
        apt-get update
        apt install -y autogen autoconf libtool openssl-devel

      - script: |
        cd $(Build.SourcesDirectory)
        autoreconf -fvi
        ./configure
        make

      - script: |
          cd src
          ./dynomite --help
